# Generated by Django 4.2.29 on 2026-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
