# Generated by Django 4.2.29 on 2026-04-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
